version: '3'
services:
  monitor:
    build: ./monitor
    container_name: django-monitor-uvicorn
    volumes:
      - static_volume:/home/monitor/monitor/staticfiles
    restart: always
    # command: "gunicorn monitor.asgi:application --bind :8000 --workers 4 -k uvicorn.workers.UvicornWorker"
    command: "gunicorn monitor.asgi:application --bind :8000 --workers 4 -k uvicorn.workers.UvicornWorker --log-level debug"
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: django-monitor-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  nginx:
    build: ./nginx
    container_name: django-monitor-nginx
    volumes:
      - static_volume:/home/monitor/monitor/staticfiles
    ports:
      - $PORT:80
    depends_on:
      - monitor

volumes:
  postgres_data:
  static_volume: