version: '3'
services:
  monitor:
    build: .
    container_name: django-monitor-uvicorn
    volumes:
      - static_volume:/var/www/app/static
    restart: on-failure
    expose:
      - 8000
    env_file:
      - .env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: django-monitor-postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
  redis:
    image: redis
    restart: on-failure
    container_name: django-monitor-redis
  
  nginx:
    build: ./nginx
    container_name: django-monitor-nginx
    restart: on-failure
    volumes:
      - static_volume:/var/www/app/static
    ports:
      - $PORT:80
    links:
      - monitor
    depends_on:
      - monitor
  

volumes:
  postgres_data:
  static_volume: